export const CULTUURKUUR_TAILORED_LABEL = 'cultuurkuur_op_maat';
export const CULTUURKUUR_ON_SITE_LABEL = 'cultuurkuur_op_verplaatsing';

export const CULTUURKUUR_LOCATION_LABELS_ERROR =
  'CULTUURKUUR_LOCATION_LABELS_ERROR';
export const CULTUURKUUR_EDUCATION_LABELS_ERROR =
  'CULTUURKUUR_EDUCATION_LABELS_ERROR';
export const CULTUURKUUR_TYPE_ERROR = 'CULTUURKUUR_TYPE_ERROR';
export const CULTUURKUUR_THEME_ERROR = 'CULTUURKUUR_THEME_ERROR';
